export const carList = [
    { "id": 1, "make": "Toyota", "model": "Hilux" },
    { "id": 2, "make": "Toyota", "model": "Land Cruiser" },
    { "id": 3, "make": "Toyota", "model": "Corolla" },
    { "id": 4, "make": "Nissan", "model": "Patrol" },
    { "id": 5, "make": "Nissan", "model": "Navara" },
    { "id": 6, "make": "Nissan", "model": "Micra" },
    { "id": 7, "make": "Hyundai", "model": "Tucson" },
    { "id": 8, "make": "Hyundai", "model": "Accent" },
    { "id": 9, "make": "Hyundai", "model": "Santa Fe" },
    { "id": 10, "make": "Kia", "model": "Sportage" },
    { "id": 11, "make": "Kia", "model": "Picanto" },
    { "id": 12, "make": "Kia", "model": "Sorento" },
    { "id": 13, "make": "Ford", "model": "Ranger" },
    { "id": 14, "make": "Ford", "model": "Focus" },
    { "id": 15, "make": "Ford", "model": "Explorer" },
    { "id": 16, "make": "Volkswagen", "model": "Tiguan" },
    { "id": 17, "make": "Volkswagen", "model": "Polo" },
    { "id": 18, "make": "Volkswagen", "model": "Amarok" },
    { "id": 19, "make": "Renault", "model": "Duster" },
    { "id": 20, "make": "Renault", "model": "Sandero" },
    { "id": 21, "make": "Renault", "model": "Koleos" },
    { "id": 22, "make": "Peugeot", "model": "3008" },
    { "id": 23, "make": "Peugeot", "model": "508" },
    { "id": 24, "make": "Peugeot", "model": "Partner" },
    { "id": 25, "make": "Mazda", "model": "CX-5" },
    { "id": 26, "make": "Mazda", "model": "Mazda 3" },
    { "id": 27, "make": "Mazda", "model": "BT-50" },
    { "id": 28, "make": "Mitsubishi", "model": "L200" },
    { "id": 29, "make": "Mitsubishi", "model": "Outlander" },
    { "id": 30, "make": "Mitsubishi", "model": "ASX" }
]